// Build the Production Tool template app (production-tool.app.clan) with the
// real `clan` CLI, and write it into src/app-template.gen.ts as base64 so the
// web app needs neither the CLI nor a fetch to create a document.
//
// The app carries the bundled document schema as agent/output-schema.json:
// every /patch-data the host applies is validated against it by the SDK.
//
// Run after a contract change: `npm run app` (needs `clan` on PATH).
import { execFileSync } from 'node:child_process'
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { bundle } from './bundle-schema.mjs'

const here = dirname(fileURLToPath(import.meta.url))
const pkg = join(here, '..')
const clan = process.env.CLAN_BIN || 'clan'
const TEMPLATE_DATA = {
  contract_version: '2',
  app: 'production-tool',
  participant: { id: 'template', handle: 'template' },
  stage: { current: 'character' },
  assets: [],
  keys: [],
  refs: [],
  jobs: [],
}
const tmp = mkdtempSync(join(tmpdir(), 'pt-app-'))
const run = args => execFileSync(clan, ['--quiet', ...args], { stdio: ['ignore', 'pipe', 'inherit'] })

try {
  const schema = join(tmp, 'schema.json')
  writeFileSync(schema, JSON.stringify(bundle(), null, 2) + '\n')
  run(['create', '--title', 'Production Tool', '--brief',
    "One participant's Production Tool document: character, script, shots, frames, takes, jobs and reviews. Write it only through patch-data; human verdicts are decision-chain entries.",
    '--output', join(tmp, 'seed.clan')])
  // The schema validates the data already there, so the template carries a
  // minimal valid document. A new instance never sees it: library
  // create_instance resets the data (fresh_data), and ClanDocumentStore.create
  // writes the real first document in one attributed patch.
  run(['pack-html', join(tmp, 'seed.clan'), join(pkg, 'app', 'index.html'), '--output', join(tmp, 'view.clan'),
    '--agent', 'clan-store', '--action', 'Production Tool summary view'])
  run(['patch-data', join(tmp, 'view.clan'), JSON.stringify(TEMPLATE_DATA), '--no-decision'])
  run(['patch-schema', join(tmp, 'view.clan'), schema])
  run(['app', 'init', '--from', join(tmp, 'view.clan'), '--name', 'Production Tool',
    '--app-id', 'production-tool', '--version', '1.0.0', '--output', join(tmp, 'app.clan')])
  run(['validate', join(tmp, 'app.clan')])
  const bytes = readFileSync(join(tmp, 'app.clan'))
  const out = join(pkg, 'src', 'app-template.gen.ts')
  writeFileSync(out, [
    '// Generated by scripts/make-app.mjs (`npm run app`). Do not edit.',
    '// The Production Tool template app, built with the clan CLI from',
    '// production-tool/contracts/document.schema.json (bundled) and app/index.html.',
    `export const APP_ID = 'production-tool'`,
    `export const APP_TEMPLATE_BASE64 =\n  '${bytes.toString('base64')}'`,
    '',
  ].join('\n'))
  console.log(`wrote ${out} (${bytes.length} bytes of .clan)`)
} finally {
  rmSync(tmp, { recursive: true, force: true })
}
